// Source library: reads the researcher's research/sources/*.json manifests,
// downloads the public-domain files marked `download: true` into vault/sources/,
// and writes research/SOURCES.md listing every source with its link.
//
//   npm run sources              download what's missing, rewrite SOURCES.md
//   npm run sources -- --dry     list what would be downloaded, write nothing
//   npm run sources -- --max 100 raise the per-file size cap (MB, default 50)
//
// vault/sources/ is gitignored: the manifests and SOURCES.md are the record,
// and this script rebuilds the local library on any machine.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST_DIR = path.join(ROOT, 'research', 'sources');
const OUT_DIR = path.join(ROOT, 'vault', 'sources');
const INDEX = path.join(ROOT, 'research', 'SOURCES.md');

const args = process.argv.slice(2);
const DRY = args.includes('--dry');
const maxIdx = args.indexOf('--max');
const MAX_MB = maxIdx >= 0 ? Number(args[maxIdx + 1]) : 50;
const MAX_BYTES = MAX_MB * 1024 * 1024;
const UA = 'TheMuse-SourceLibrary/1.0 (+https://github.com/mattglbrt/themuse)';
const SAFE_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*\.[a-z0-9]+$/;

const mb = (n) => `${(n / 1024 / 1024).toFixed(1)} MB`;

function loadManifests() {
  if (!fs.existsSync(MANIFEST_DIR)) return [];
  const entries = [];
  for (const f of fs.readdirSync(MANIFEST_DIR).filter((f) => f.endsWith('.json')).sort()) {
    let data;
    try {
      data = JSON.parse(fs.readFileSync(path.join(MANIFEST_DIR, f), 'utf8'));
    } catch (e) {
      console.error(`✗ ${f}: not valid JSON (${e.message})`);
      process.exitCode = 1;
      continue;
    }
    for (const s of data.sources ?? []) entries.push({ ...s, memo: data.memo ?? f.replace(/\.json$/, '.md') });
  }
  return entries;
}

async function download(s) {
  if (!SAFE_NAME.test(s.filename ?? '')) return { ok: false, why: `unsafe filename "${s.filename}"` };
  const dest = path.join(OUT_DIR, s.filename);
  if (fs.existsSync(dest)) return { ok: true, bytes: fs.statSync(dest).size, existed: true };
  if (DRY) return { ok: false, why: 'dry run', dry: true };

  let res;
  try {
    res = await fetch(s.file, { headers: { 'User-Agent': UA }, redirect: 'follow' });
  } catch (e) {
    return { ok: false, why: `fetch failed (${e.cause?.code ?? e.message})` };
  }
  if (!res.ok) return { ok: false, why: `HTTP ${res.status}` };
  const type = res.headers.get('content-type') ?? '';
  // A landing page served in place of the file is the usual failure; don't save it as a "source".
  if (type.includes('text/html') && s.format !== 'html') return { ok: false, why: `got an HTML page, not a ${s.format}` };
  const len = Number(res.headers.get('content-length') ?? 0);
  if (len > MAX_BYTES) return { ok: false, why: `too large (${mb(len)}; cap ${MAX_MB} MB)`, big: true };

  const part = `${dest}.part`;
  const out = fs.createWriteStream(part);
  const hash = crypto.createHash('sha256');
  let bytes = 0;
  try {
    for await (const chunk of res.body) {
      bytes += chunk.length;
      if (bytes > MAX_BYTES) throw Object.assign(new Error(`too large (over ${MAX_MB} MB)`), { big: true });
      hash.update(chunk);
      if (!out.write(chunk)) await new Promise((r) => out.once('drain', r));
    }
    await new Promise((r, j) => out.end((e) => (e ? j(e) : r())));
  } catch (e) {
    out.destroy();
    fs.rmSync(part, { force: true });
    return { ok: false, why: e.message, big: e.big };
  }
  fs.renameSync(part, dest);
  return { ok: true, bytes, sha256: hash.digest('hex') };
}

const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const link = (label, url) => (url ? `[${cell(label)}](${url})` : '');
const memoLink = (m) => `[${m.replace(/\.md$/, '')}](${m})`;

function writeIndex(rows) {
  const inVault = rows.filter((r) => r.result?.ok);
  const pdManual = rows.filter((r) => !r.result?.ok && r.rights === 'public-domain');
  const elsewhere = rows.filter((r) => !r.result?.ok && r.rights !== 'public-domain');
  const obtain = (r) =>
    [link(r.host || 'Copy', r.page), ...(r.obtain ?? []).map((o) => (typeof o === 'string' ? (/^https?:\/\//.test(o) ? link(new URL(o).hostname, o) : cell(o)) : link(o.label, o.url)))]
      .filter(Boolean)
      .join(' · ');

  const out = [
    '# Source library',
    '',
    'Generated by `npm run sources` from `research/sources/*.json`. Do not edit by hand; fix the JSON and rerun.',
    'The files themselves are not in the repo. `npm run sources` downloads the first list into `vault/sources/` (gitignored, local only), or use the links below.',
    '',
    `## Public domain: download links (${inVault.length})`,
    '',
    'Fetched by `npm run sources` into `vault/sources/`.',
    '',
    '| Work | Edition | Download | Local file | Copy terms | Memo |',
    '|---|---|---|---|---|---|',
    ...inVault.map((r) => `| ${cell(r.work)} | ${cell(r.edition)} | ${link(`${r.format ?? 'file'}, ${mb(r.result.bytes)}`, r.file)} · ${link(r.host, r.page)} | \`${r.filename}\` | ${cell(r.copyTerms)}${r.approved ? ` **${cell(r.approved)}.**` : ''} | ${memoLink(r.memo)} |`),
    '',
    `## Public domain, download it yourself (${pdManual.length})`,
    '',
    'The work is public domain but the file was not fetched automatically. The reason says why.',
    '',
    '| Work | Edition | Get it | Reason | Memo |',
    '|---|---|---|---|---|',
    ...pdManual.map((r) => {
      const why = r.result ? r.result.why : r.download ? 'not attempted' : `not marked for download: ${cell(r.copyTerms) || 'no direct file or copy terms unclear'}`;
      return `| ${cell(r.work)} | ${cell(r.edition)} | ${[link('file', r.file), obtain(r)].filter(Boolean).join(' · ')} | ${cell(why)} | ${memoLink(r.memo)} |`;
    }),
    '',
    `## In copyright or unclear: where to get it (${elsewhere.length})`,
    '',
    '| Work | Edition | Rights | Where to get it | Memo |',
    '|---|---|---|---|---|',
    ...elsewhere.map((r) => `| ${cell(r.work)} | ${cell(r.edition)} | ${cell(r.rights)}${r.rightsBasis ? `: ${cell(r.rightsBasis)}` : ''} | ${obtain(r)} | ${memoLink(r.memo)} |`),
    '',
  ];
  fs.writeFileSync(INDEX, out.join('\n'));
}

const entries = loadManifests();
if (!entries.length) {
  console.log('No manifests in research/sources/. Nothing to do.');
  process.exit();
}
fs.mkdirSync(OUT_DIR, { recursive: true });

// The same file can be cited by several memos; fetch it once.
const seen = new Map();
for (const s of entries) {
  // `approved` records Matt's own call to download a copy whose rights or terms the researcher couldn't settle.
  if (!(s.download && s.file && (s.rights === 'public-domain' || s.approved))) continue;
  if (!seen.has(s.filename)) {
    seen.set(s.filename, download(s));
  }
  s.result = await seen.get(s.filename);
  const r = s.result;
  const tag = r.ok ? (r.existed ? '·' : '↓') : r.dry ? '?' : '✗';
  console.log(`${tag} ${s.filename}${r.ok ? ` (${mb(r.bytes)})` : ` — ${r.why}`}`);
  if (r.sha256) console.log(`  sha256 ${r.sha256}`);
}

if (DRY) {
  console.log('\nDry run: nothing written.');
} else {
  writeIndex(entries);
  const got = entries.filter((s) => s.result?.ok).length;
  const failed = entries.filter((s) => s.result && !s.result.ok).length;
  console.log(`\n${entries.length} sources · ${got} in vault/sources/ · ${failed} failed · SOURCES.md written`);
}
